# Site
repository: ZhengYanXU/ZhengYanXU.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: XuZhengyan
#title: Senior Network System Administrator
email: xuzhengyan@nuaa.edu.cn
website: https://zhengyanxu.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: zhengyanxu
github_username:  zhengyanxu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  个人简介
  - 姓名：徐峥岩
  - 年级：2022级硕士
  - 学院：南京航空航天大学计算机科学与技术学院
  - 导师：梁栋 副教授
  - 邮箱：XuZhengYan@nuaa.edu.cn
content:
  - title: 教育经历 # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      2017 - 2021: 合肥工业大学 计算机科学与技术、2022 - 今  : 南京航空航天大学 电子信息
  - title: 研究方向
    layout: text
    content: | # this will include new lines to allow paragraphs
      我的研究兴趣包括：图像增强、计算机摄影学、图像分割、对比学习等

  - title: 论文
    layout: text
    content: | # this will include new lines to allow paragraphs
    《PIE: Physics-inspired Low-light Enhancement》(IJCV，已发表，CCF-A,导师一作，实际撰写人）
    《Beyond the limits: Tackling Extreme Overexposure with Diffusion Model》(ICIC2024，已发表,CCF-C,一作）
  - title: 专利
    layout: text
    content: | # this will include new lines to allow paragraphs
    《一种物理驱动的用于低光图像增强的对比学习方法》(已授权)
    《一种语义引导的极端过曝图像修复方法》（已提交）
     

  


# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
